-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."trans_leave_request_lines" add column "request_type_id" serial
--  not null;
