-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."trans_leave_request_attachments" add column "attachment" text
--  null default 'Filename Data Type';
